name: Run Tests for Changed Activities

on:
  push:
    paths:
      - 'activities/**'
  pull_request:
    paths:
      - 'activities/**'

jobs:
  selective-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Get changed activity files
        id: changes
        run: |
          echo "files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^activities/' || true)" >> $GITHUB_OUTPUT

      - name: Run relevant unittest tests
        if: steps.changes.outputs.files != ''
        run: |
          for file in ${{ steps.changes.outputs.files }}; do
            name=$(basename "$file" .py)
            test_file="tests/test_${name}.py"
            if [ -f "$test_file" ]; then
              echo "Running: python -m unittest ${test_file%.*}"
              python -m unittest "${test_file%.*}"
            else
              echo "No test file found for $file"
            fi
          done

